version: "5"
services:
  main_database:
    image: "postgres:latest"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  client:
    ports:
      - "3000:3000"
    build:
      context: ./client

  server:
    depends_on:
      - main_database
    restart: always
    ports:
      - "3002:3002"
    build:
      context: ./server
      args:
        SERVER_PORT: 3002
        DATABASE_HOST: 172.17.0.1
        DATABASE_PORT: 5433
        DATABASE_NAME: postgres
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: postgres

        CLIENT_ORIGIN: #secret

        JWT_KEY: grgIBEIHBriiBhibIHB
        COOKIE_KEY: ibirbg8hjerbgkerjg